# site settings
title: 蒋肇锦
author: 蒋肇锦
email: 1223870172@qq.com
description: 蒋肇锦的博客
github_username: Zebrass
permalink: /:year/:month/:day/:title/
baseurl: https://zebrass.github.io

# Build settings
markdown: kramdown
gems: [jekyll-paginate]

# Page setting
paginate: 10
paginate_path: "page:num"
